program LayoutPages;

uses
  Vcl.Forms,
  LayoutPages.View.Forms.FormDefault in 'source\layoutpages\view\forms\LayoutPages.View.Forms.FormDefault.pas' {FormDefault},
  LayoutPages.View.Forms.BackgroundLayout in 'source\layoutpages\view\forms\LayoutPages.View.Forms.BackgroundLayout.pas' {FormBackgroundLayout},
  LayoutPages.View.Forms.DefaultBoxTemplate in 'source\layoutpages\view\forms\LayoutPages.View.Forms.DefaultBoxTemplate.pas' {FormDefaultBoxTemplate},
  LayoutPages.View.Forms.DefaultTemplate in 'source\layoutpages\view\forms\LayoutPages.View.Forms.DefaultTemplate.pas' {FormDefaultTemplate},
  LayoutPages.View.Forms.CadastroPrincipal in 'source\layoutpages\view\forms\LayoutPages.View.Forms.CadastroPrincipal.pas' {FormCadastrosPrincipal},
  LayoutPages.View.Componentes.BotoesBarraClose in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.BotoesBarraClose.pas' {CmpBotoesBarraClose},
  LayoutPages.View.Componentes.TCheckbox in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.TCheckbox.pas',
  LayoutPages.View.Componentes.TComboboxTitulo in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.TComboboxTitulo.pas',
  LayoutPages.View.Componentes.TDateEditTitulo in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.TDateEditTitulo.pas',
  LayoutPages.View.Componentes.TEditPesquisa in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.TEditPesquisa.pas',
  LayoutPages.View.Componentes.TEditTitulo in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.TEditTitulo.pas',
  LayoutPages.View.Componentes.TLabelTitulo in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.TLabelTitulo.pas',
  LayoutPages.View.Componentes.BotoesBarraOpcoes in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.BotoesBarraOpcoes.pas' {CmpBotoesBarra},
  LayoutPages.View.Componentes.MenuImage in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.MenuImage.pas' {CmpMenuImage},
  LayoutPages.View.Componentes.CardInfoUser in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.CardInfoUser.pas' {CmpCardInfoUser},
  LayoutPages.View.Componentes.TituloDescricaoSimples in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.TituloDescricaoSimples.pas' {CmpTituloDescSimples},
  LayoutPages.View.Componentes.ControlGrid in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.ControlGrid.pas' {CmpGridControl},
  LayoutPages.View.Componentes.FormGrid in 'source\layoutpages\view\componentes\LayoutPages.View.Componentes.FormGrid.pas' {CmpFormGrid},
  ConhecFrete.Model.DAO.Cliente in 'source\SEDF\model\dao\ConhecFrete.Model.DAO.Cliente.pas',
  ConhecFrete.Model.DAO.Regiao in 'source\SEDF\model\dao\ConhecFrete.Model.DAO.Regiao.pas',
  ConhecFrete.Model.DAO.Simplificado in 'source\SEDF\model\dao\ConhecFrete.Model.DAO.Simplificado.pas',
  ConhecFrete.Model.DAO.SituacaoCarregamento in 'source\SEDF\model\dao\ConhecFrete.Model.DAO.SituacaoCarregamento.pas',
  ConhecFrete.Model.DAO.UFGlobalizado in 'source\SEDF\model\dao\ConhecFrete.Model.DAO.UFGlobalizado.pas',
  ConhecFrete.Model.DTO.Cte in 'source\SEDF\model\dto\ConhecFrete.Model.DTO.Cte.pas',
  ConhecFrete.Model.DTO.DadosClienteFrete in 'source\SEDF\model\dto\ConhecFrete.Model.DTO.DadosClienteFrete.pas',
  ConhecFrete.Model.DTO.DadosColeta in 'source\SEDF\model\dto\ConhecFrete.Model.DTO.DadosColeta.pas',
  ConhecFrete.Model.DTO.DadosPedagio in 'source\SEDF\model\dto\ConhecFrete.Model.DTO.DadosPedagio.pas',
  ConhecFrete.Model.DTO.DadosTributacao in 'source\SEDF\model\dto\ConhecFrete.Model.DTO.DadosTributacao.pas',
  ConhecFrete.Model.DTO.FiltrosSimulacaoCte in 'source\SEDF\model\dto\ConhecFrete.Model.DTO.FiltrosSimulacaoCte.pas',
  ConhecFrete.Model.Types.Constantes in 'source\SEDF\model\types\ConhecFrete.Model.Types.Constantes.pas',
  ConhecFrete.View.Componentes.OpcoesGerarCte in 'source\SEDF\view\componentes\ConhecFrete.View.Componentes.OpcoesGerarCte.pas' {CmpOpcoesGerarCte},
  ConhecFrete.View.Componentes.CardInfoUserCte in 'source\SEDF\view\componentes\ConhecFrete.View.Componentes.CardInfoUserCte.pas' {CmpCardInfoUserCte},
  ConhecFrete.View.Componentes.BarraTituloCadastroProdutos in 'source\SEDF\view\componentes\ConhecFrete.View.Componentes.BarraTituloCadastroProdutos.pas' {CmpBarraTituloCadastroProdutos},
  ConhecFrete.View.Componentes.BarraItemCadastroProdutos in 'source\SEDF\view\componentes\ConhecFrete.View.Componentes.BarraItemCadastroProdutos.pas' {CmpBarraItemCadastroProdutos},
  ConhecFrete.View.Componentes.BarraItemCadastroServicos in 'source\SEDF\view\componentes\ConhecFrete.View.Componentes.BarraItemCadastroServicos.pas' {CmpBarraItemCadastroServicos},
  ConhecFrete.View.Componentes.BarraItemCadastroClientes in 'source\SEDF\view\componentes\ConhecFrete.View.Componentes.BarraItemCadastroClientes.pas' {CmpBarraItemCadastroClientes},
  ConhecFrete.View.Componentes.BarraItemCadastroFornecedores in 'source\SEDF\view\componentes\ConhecFrete.View.Componentes.BarraItemCadastroFornecedores.pas' {CmpBarraItemCadastroFornecedores},
  ConhecFrete.View.Componentes.BarraItemCadastroTransportadoras in 'source\SEDF\view\componentes\ConhecFrete.View.Componentes.BarraItemCadastroTransportadoras.pas' {CmpBarraItemCadastroTransportadoras},
  ConhecFrete.View.Componentes.BarraItemCadastroMarcas in 'source\SEDF\view\componentes\ConhecFrete.View.Componentes.BarraItemCadastroMarcas.pas' {CmpBarraItemCadastroMarcas},
  ConhecFrete.View.Componentes.BarraItemCadastroUnidadesDeMedida in 'source\SEDF\view\componentes\ConhecFrete.View.Componentes.BarraItemCadastroUnidadesDeMedida.pas' {CmpBarraItemCadastroUnidadesDeMedida},
  ConhecFrete.Controller.ClienteDadosCte in 'source\SEDF\controller\ConhecFrete.Controller.ClienteDadosCte.pas',
  ConhecFrete.Controller.DadosPedagioSeguro in 'source\SEDF\controller\ConhecFrete.Controller.DadosPedagioSeguro.pas',
  ConhecFrete.Controller.Motorista in 'source\SEDF\controller\ConhecFrete.Controller.Motorista.pas',
  ConhecFrete.Controller.Parametros in 'source\SEDF\controller\ConhecFrete.Controller.Parametros.pas',
  ConhecFrete.Controller.Principal in 'source\SEDF\controller\ConhecFrete.Controller.Principal.pas',
  ConhecFrete.Controller.RegiaoDadosCte in 'source\SEDF\controller\ConhecFrete.Controller.RegiaoDadosCte.pas',
  ConhecFrete.Controller.SimplificadoDadosCte in 'source\SEDF\controller\ConhecFrete.Controller.SimplificadoDadosCte.pas',
  ConhecFrete.Controller.SituacaoCarregamento in 'source\SEDF\controller\ConhecFrete.Controller.SituacaoCarregamento.pas',
  ConhecFrete.Controller.Tomador in 'source\SEDF\controller\ConhecFrete.Controller.Tomador.pas',
  ConhecFrete.Controller.UFGlobalizadoDadosCte in 'source\SEDF\controller\ConhecFrete.Controller.UFGlobalizadoDadosCte.pas',
  ConhecFrete.Controller.MenuCte in 'source\SEDF\controller\ConhecFrete.Controller.MenuCte.pas',
  ConhecFrete.Controller.BotoesBarraOpcoes in 'source\SEDF\controller\ConhecFrete.Controller.BotoesBarraOpcoes.pas',
  ConhecFrete.Controller.OpcoesItens in 'source\SEDF\controller\ConhecFrete.Controller.OpcoesItens.pas',
  ConhecFrete.Controller.OpcoesInicio in 'source\SEDF\controller\ConhecFrete.Controller.OpcoesInicio.pas',
  ConhecFrete.Controller.MenuCadastros in 'source\SEDF\controller\ConhecFrete.Controller.MenuCadastros.pas',
  ConhecFrete.Controller.MenuEmissaoFiscal in 'source\SEDF\controller\ConhecFrete.Controller.MenuEmissaoFiscal.pas',
  ConhecFrete.Controller.MenuItensImagens in 'source\SEDF\controller\ConhecFrete.Controller.MenuItensImagens.pas',
  ConhecFrete.Controller.Cadastros in 'source\SEDF\controller\cadastros\ConhecFrete.Controller.Cadastros.pas',
  ConhecFrete.Controller.Cadastros.Produtos in 'source\SEDF\controller\cadastros\ConhecFrete.Controller.Cadastros.Produtos.pas',
  ConhecFrete.Controller.Cadastros.Servicos in 'source\SEDF\controller\cadastros\ConhecFrete.Controller.Cadastros.Servicos.pas',
  ConhecFrete.Controller.Cadastros.Clientes in 'source\SEDF\controller\cadastros\ConhecFrete.Controller.Cadastros.Clientes.pas',
  ConhecFrete.Controller.Cadastros.Marcas in 'source\SEDF\controller\cadastros\ConhecFrete.Controller.Cadastros.Marcas.pas',
  ConhecFrete.Controller.Cadastros.Transportadoras in 'source\SEDF\controller\cadastros\ConhecFrete.Controller.Cadastros.Transportadoras.pas',
  ConhecFrete.Controller.Cadastros.Fornecedores in 'source\SEDF\controller\cadastros\ConhecFrete.Controller.Cadastros.Fornecedores.pas',
  ConhecFrete.Controller.Cadastros.UnidadesDeMedida in 'source\SEDF\controller\cadastros\ConhecFrete.Controller.Cadastros.UnidadesDeMedida.pas',
  ConhecFrete.Forms.Cte.Cliente.DadosCte in 'source\SEDF\view\forms\cte\cliente\ConhecFrete.Forms.Cte.Cliente.DadosCte.pas' {frmClienteDadosCte},
  ConhecFrete.Forms.Cte.RegiaoDadosCte in 'source\SEDF\view\forms\cte\regiao\ConhecFrete.Forms.Cte.RegiaoDadosCte.pas' {frmRegiaoDadosCte},
  ConhecFrete.Forms.Cte.UFGlobalizado.DadosCte in 'source\SEDF\view\forms\cte\ufglobalizado\ConhecFrete.Forms.Cte.UFGlobalizado.DadosCte.pas' {frmUFGlobalizadoDadosCte},
  ConhecFrete.Forms.Cte.DadosPedagioSeguro in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.DadosPedagioSeguro.pas' {frmDadosPedagioSeguro},
  ConhecFrete.Forms.Cte.GridSimulacao in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.GridSimulacao.pas' {frmGridSimulacaoCte},
  ConhecFrete.Forms.Cte.OpcoesItens in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.OpcoesItens.pas' {FormOpcoesItensCte},
  ConhecFrete.Forms.Cte.Motorista in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.Motorista.pas' {frmCteMotorista},
  ConhecFrete.Forms.Cte.OpcoesInicio in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.OpcoesInicio.pas' {frmCteOpcoesInicio},
  ConhecFrete.Forms.Cte.Parametros in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.Parametros.pas' {frmCteParametros},
  ConhecFrete.Forms.Cte.SubContratacao in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.SubContratacao.pas' {frmCteSimplificadoSubContratacao},
  ConhecFrete.Forms.Cte.Tomador in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.Tomador.pas' {frmTomador},
  ConhecFrete.Forms.Cte.Simplificado.DadosCte in 'source\SEDF\view\forms\cte\simplificado\ConhecFrete.Forms.Cte.Simplificado.DadosCte.pas' {frmSimplificadoDadosCte},
  ConhecFrete.Forms.Cte.Simplificado.InfoRegrasCteSimplificado in 'source\SEDF\view\forms\cte\simplificado\ConhecFrete.Forms.Cte.Simplificado.InfoRegrasCteSimplificado.pas' {frmCteSimplificadoInfoRegras},
  ConhecFrete.Forms.Cte.Principal in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.Principal.pas' {frmCtePrincipal},
  ConhecFrete.Forms.Cte.Background in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.Background.pas' {FormCteBackground},
  ConhecFrete.Forms.Cte.MenuPrincipal in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.MenuPrincipal.pas' {FormMenuPrincipal},
  ConhecFrete.Forms.Cte.MenuEmissaoFiscal in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.MenuEmissaoFiscal.pas' {FormMenuEmissaoFiscal},
  ConhecFrete.Forms.Cte.MenuCadastros in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.MenuCadastros.pas' {FormMenuCadastros},
  ConhecFrete.Forms.Cte.MenuItensImagens in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.MenuItensImagens.pas' {FormMenuItensImagens},
  ConhecFrete.Forms.Cte.Cadastros in 'source\SEDF\view\forms\cte\ConhecFrete.Forms.Cte.Cadastros.pas' {FormCteCadastros};

{$R *.res}

begin
  //ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFormCteBackground, FormCteBackground);
  Application.Run;
end.
